### ISSUE TITLE
No module named skvideo

### ISSUE THREAD

**Issue by ABDOELSHEMY** [ravisvi/super-resolution-videos#1]
hi @ravisvi 
thank you for sharing this great work with us.
Unfortunately, when i try to use it, i get this error

**python supervideo.py
Traceback (most recent call last):
  File "supervideo.py", line 4, in <module>
    import video_super_resolver as vsr
  File "G:\idm\super-resolution-videos-master_2\video_super_resolver.py", line 10, in <module>
    import skvideo.io
ImportError: No module named 'skvideo'**

 how can to solve this please.

**Comment by kevinjoseph1995** [comment]
@ABDOELSHEMY  http://www.scikit-video.org/stable/

**Comment by ABDOELSHEMY** [comment]
OK, thank you @kevinjoseph1995.
