### ISSUE TITLE
Can I use GPU?

### ISSUE THREAD

**Issue by kokosandim** [ravisvi/super-resolution-videos#5]
I have gtx 1070, how I can run this render on gpu?
I dont find where I can specify this

**Comment by ravisvi** [comment]
Hi @kokosandim, 

Hmm. The answer is mostly no. 

You _can_ use your GPU to **train** the models. This happens automatically if you have tensor flow installed with CUDA. 

If you are talking about using the existing models in this repository and super-resolving videos using the supervideo.py then there is currently no way of specifying to the code base to use the GPU. 
However, if you are using tensor flow with CUDA and if your FFmpeg binary is compiled with the required support for NVIDIA libraries then, your computer should automatically use the graphics card I assume. But I'm not sure of this. Please have a look at this link here: https://developer.nvidia.com/ffmpeg

Make sure you are using the right FFmpeg binary _after_ you get the one from above.
