### ISSUE TITLE
How to change upscaling factor?

### ISSUE THREAD

**Issue by Picslook** [ravisvi/super-resolution-videos#7]

**Comment by mzy2240** [comment]
@ravisvi Is there any way to change the output resolution?

**Comment by ravisvi** [comment]
@kevinjoseph1995 Hey Kevin, I couldn't find any config for this that can easily change the upscaling factor. Would changing this https://github.com/ravisvi/super-resolution-videos/blob/master/model.py#L98 do the trick?

**Comment by kevinjoseph1995** [comment]
It looks like output dimensions are not configurable as the number of
SubpixelConv2d(which does the upsampling of each feature layer) layers were
hard coded.  But I'm sure the output-scale multiplicative factor is simply
controlled by the number of the SubpixelConv2d layers in the generator.

Note: If this was modified an equivalent change has to be made to the
discriminator to ensure equal down-sampling.


On Tue, Dec 31, 2019 at 8:32 AM Ravi Tejasvi <notifications@github.com>
wrote:
>
> @kevinjoseph1995 Hey Kevin, I couldn't find any config for this that can
easily change the upscaling factor. Would changing this
https://github.com/ravisvi/super-resolution-videos/blob/master/model.py#L98
do the trick?
